accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import create_user


urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="registration/logout.html"
        ),
        name="logout",
    ),
    path(
        "signup/",
        create_user,
        name="signup",
    ),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("dashboard/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        "auth.User",
        related_name="projects",
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.conf import settings

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.


def create_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        print(Project.objects.filter(members=self.request.user))
        return Project.objects.filter(members=self.request.user)

    #     # return Project.objects.all


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = [
        "name",
        "description",
        "members",
    ]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse
from projects.models import Project
from tasks.models import Task
import datetime

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        projectlist = []

        print(datetime.datetime.now())
        # print(Task.due_date)
        # delta = d1 - d0
        # print(delta)
        # Create a new empty list and assign it to a variable

        for proj in self.request.user.projects.all():
            projectlist.append(proj.name)
        context["projects_list"] = projectlist
        context["projects"] = Project.objects.filter(members=self.request.user)
        # Put that list into the context
        return context

    # def get_queryset(self):
    #     print(Task.project.all)
    #     return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/list.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tracker</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>

    <body>
        <header>
            <nav>
                <ul class = "horizontal">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}"> Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My Projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}

{% block content %}
    {% load markdownify %}
    <main>
        <div>
            <h1>{{ project.name }}</h1>
            <p>{{ project.description|markdownify }}</p>
            <h2>Tasks</h2>
            <a href="{% url 'create_task' %}">Create a new task</a>
            {% if project.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            {% if task.assignee == user %}
                                <tr>
                                    <td> {{ task.name }} </td>
                                    <td> {{ task.assignee}} </td>
                                    <td> {{ task.start_date}} </td>
                                    <td> {{ task.due_date}} </td>
                                    <td> {{ task.is_completed}} </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Projects</h1>
            <a href="{% url 'create_project' %}">Create a new project</a>
            {% if project_list %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td> <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a> </td>
                                <td> {{ project.tasks.all|length }} </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% load upcomingtasks %}

{% block content %}
    <main>
        <div>
            <h2>Upcoming Tasks Due</h2>
            {% if True %}
            {% for task in task_list %}
            {{ task.due_date|upcoming }}
            {% endfor %}
            {% else %}
            <img src="https://memegenerator.net/img/instances/78104397.jpg" style="align: left;">
            <p>
                Wow... nice job, no upcoming tasks. It appears you're an overachiever. 
                Thanks for making everyone feel bad. 
            
            </p>
            {% endif %}
        </div> 
            <h2>My Projects</h2> 
            <div class="tooltip">
                <span><a href="{% url 'create_task' %}">Create A Lot More Work</a></span>
                    <p class= "tooltiptext">Don't have enough unfinished work? Create a new project ya psycho!</p>
            </div>
            {% if projects %}
                <table>
                    <thead>
                        <tr>
                            <th>Project</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td> <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a> </td>
                                <td> {{ project.description }} </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
            <div>
                <canvas id="myChart" width="400" height="400"></canvas>
                <script>
                    var ctx = document.getElementById("myChart");
                    var myChart = new Chart(ctx, {
                      type: 'pie',
                      data: {
                        labels: ['Uncomplete', 'Urgent', 'Complete'],
                        datasets: [{
                          label: '# of Tomatoes',
                          data: [6, 1, 1],
                          backgroundColor: [
                            'rgba(255, 99, 132, 0.5)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)'
                          ],
                          borderColor: [
                            'rgba(255,99,132,1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)'
                          ],
                          borderWidth: 1
                        }]
                      },
                      options: {
                           //cutoutPercentage: 40,
                        responsive: false,
                    
                      }
                    });
                </script>
            <div>
            {% if task_list %}
            <p></p>
                <h2>My Tasks</h2>
            <p></p>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td> {{ task.name }} </td>
                                <td> {{ task.start_date|date:"D, M d y" }} </td>
                                <td> {{ task.due_date|date:"D, M d y" }} </td>
                                <td>
                                    {% if task.is_completed == False %}
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button>Complete</button>
                                        </form>
                                    {% else %}
                                        Done
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}